-l"ti/sdo/ce/video2/split/lib/release/viddec2front.ae674"
-l"ti/sdo/ce/video2/split/lib/release/viddec2back.ae674"
-l"ti/sdo/ce/universal/lib/release/universal.ae674"
-l"ti/sdo/ce/vidanalytics/lib/release/vidanalytics.ae674"
-l"ti/sdo/ce/vidtranscode/lib/release/vidtranscode.ae674"
-l"ti/sdo/ce/audio1/lib/release/auddec1.ae674"
-l"ti/sdo/ce/audio1/lib/release/audenc1.ae674"
-l"ti/sdo/ce/speech1/lib/release/sphdec1.ae674"
-l"ti/sdo/ce/speech1/lib/release/sphenc1.ae674"
-l"ti/sdo/ce/image1/lib/release/imgdec1.ae674"
-l"ti/sdo/ce/image1/lib/release/imgenc1.ae674"
-l"ti/sdo/ce/video1/lib/release/viddec1.ae674"
-l"ti/sdo/ce/video1/lib/release/videnc1.ae674"
-l"ti/sdo/ce/video2/lib/release/viddec2.ae674"
-l"ti/sdo/ce/video2/lib/release/videnc2.ae674"
-l"ti/sdo/ce/video3/lib/release/viddec3.ae674"
-l"ti/sdo/ce/audio/lib/release/audio.ae674"
-l"ti/sdo/ce/image/lib/release/image.ae674"
-l"ti/sdo/ce/speech/lib/release/speech.ae674"
-l"ti/sdo/ce/video/lib/release/video.ae674"

-l"ti/sdo/ce/lib/release/ce.ae674"
-l"ti/sdo/ce/ipc/bios/lib/release/ipc_bios.ae674"
-l"ti/sdo/ce/alg/lib/release/Algorithm_BIOS.ae674"
-l"ti/sdo/ce/osal/bios/lib/release/osal.ae674"
-l"ti/sdo/ce/osal/lib/release/osal.ae674"
-l"ti/sdo/ce/node/lib/release/node.ae674"
-l"ti/sdo/ce/global/lib/release/cesettings.ae674"

/* Framework Components libraries */
-l"ti/sdo/fc/dskt2/lib/release/dskt2.ae674"
-l"ti/sdo/fc/utils/osalsupport/lib/release/osal_support.ae674"
-l"ti/sdo/fc/global/lib/release/fcsettings.ae674"

-l"ti/sdo/ce/utils/syscbuf/lib/release/syscbuf.ae674"
-l"ti/sdo/ce/utils/xdm/lib/release/XdmUtils.ae674"
